packages:
  - app
  - core/design-system
  - core/internationalization/*
  - core/linters/*
  - core/tests/*
  - core/toolkit
  - micro-apps
  - mother-frontend
  - mother-frontend/micro-apps
  - mother-frontend/micro-services
