packages:
  - app
  - core/ci-cd
  - core/configs
  - core/design-system
  - core/internationalization/*
  - core/linters
  - core/linters/*
  - core/tests/*
  - core/toolkit
  - docs
  - micro-apps
  - micro-services
