#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm install
echo "✅ Packages installed successfully!"

pnpm --filter @windows98/ci-cd build
echo "✅ The workspaces have been built successfully!"
