#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm --filter @windows98/ci-cd run lint:types:run:all
echo "✅ The types are okay!"

pnpm --filter @windows98/ci-cd run lint:code:run:all
echo "✅ The code is okay!"

pnpm --filter @windows98/ci-cd run lint:styles:run:all
echo "✅ The styles are okay!"

pnpm --filter @windows98/vitest run test:unit:run
echo "✅ The tests are okay!"

pnpm --filter @windows98/ci-cd run lint:staged:fix:all 
echo "✅ The files are okay!"
