name: CI/CD

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      reason:
        description: 'Why are you running manually?'
        required: true

jobs:
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3.5.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm dependencies and Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Install Cypress
        run: npx cypress install

  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3.5.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Check types
        run: pnpm --filter @windows98/tsc run lint:types

  eslint-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    needs: type-check
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3.5.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Lint with ESLint
        run: pnpm --filter @windows98/eslint run lintfix:js

  prettier-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    needs: type-check
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3.5.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Lint with Prettier
        run: pnpm --filter @windows98/prettier run lintfix:prettier

  stylelint-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    needs: type-check
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3.5.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Lint with Stylelint
        run: pnpm --filter @windows98/stylelint run lint:styles

  vitest-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    needs: [eslint-lint, prettier-lint, stylelint-lint]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3.5.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Run Vitest tests
        run: pnpm run vitest:run

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    needs: vitest-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Build Application
        run: pnpm run app:build

  cypress-component-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.0]
    needs: build
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3.5.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Run Cypress test
        uses: cypress-io/github-action@v5
        with:
          component: true
          command: pnpm run cypress:run

  deploy-preview:
    runs-on: ubuntu-latest
    needs: cypress-component-tests
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Install Vercel CLI Locally
        run: pnpm add vercel@latest

      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
