name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  install-cache:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.12.0]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2.7.0
      - name: 'Install Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install --force --non-interactive

  type-check:
    runs-on: macos-latest
    strategy:
      matrix:
        node:
          - 18.12.0
    needs:
      - install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2.7.0
      - name: 'Install Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - name: Restore npm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Check types
        run: npm run typecheck

  eslint-lint:
    runs-on: macos-latest
    strategy:
      matrix:
        node:
          - 18.12.0
    needs:
      - type-check
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2.7.0
      - name: 'Install Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - name: Restore npm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Lint with ESLint
        run: 'npm run lint:js'

  prettier-lint:
    runs-on: macos-latest
    strategy:
      matrix:
        node:
          - 18.12.0
    needs:
      - type-check
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2.7.0
      - name: 'Install Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - name: Restore npm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Lint with Prettier
        run: 'npm run lint:prettier'

  stylelint-lint:
    runs-on: macos-latest
    strategy:
      matrix:
        node:
          - 18.12.0
    needs:
      - type-check
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2.7.0
      - name: 'Install Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - name: Restore npm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Lint with Stylelint
        run: 'npm run lint:styles'

  vitest-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        node:
          - 18.12.0
    needs:
      - eslint-lint
      - prettier-lint
      - stylelint-lint
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2.7.0
      - name: 'Install Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - name: Restore npm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Run Vitest tests
        run: 'npm run test:run'

  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node:
          - 18.12.0
    needs:
      - vitest-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.7.0
      - name: 'Install Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - name: Restore npm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Build Application
        run: npm run build

  cypress-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        node:
          - 18.12.0
    needs:
      - build
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2.7.0
      - name: 'Install Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - name: Restore npm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Run Cypress tests
        run: 'npm run cypress:run'
        env:
          CYPRESS_BASE_URL: 'http://localhost:3000'
